sudo: required
services:
  - docker

before_install:
  - docker build -t hunt825a/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hunt825a/react-test npm test -- --coverage

after_success:
  - docker build -t hunt825a/multi-client ./client
  - docker build -t hunt825a/multi-nginx ./nginx
  - docker build -t hunt825a/multi-server ./server
  - docker build -t hunt825a/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push hunt825a/multi-client
  - docker push hunt825a/multi-nginx
  - docker push hunt825a/multi-server
  - docker push hunt825a/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket-name: elasticbeastalk-blabla
#  bucket-path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
